# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Error(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, tite: str=None, status: int=None, detail: str=None, type: str=None):  # noqa: E501
        """Error - a model defined in Swagger

        :param tite: The tite of this Error.  # noqa: E501
        :type tite: str
        :param status: The status of this Error.  # noqa: E501
        :type status: int
        :param detail: The detail of this Error.  # noqa: E501
        :type detail: str
        :param type: The type of this Error.  # noqa: E501
        :type type: str
        """
        self.swagger_types = {
            'tite': str,
            'status': int,
            'detail': str,
            'type': str
        }

        self.attribute_map = {
            'tite': 'tite',
            'status': 'status',
            'detail': 'detail',
            'type': 'type'
        }

        self._tite = tite
        self._status = status
        self._detail = detail
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'Error':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Error of this Error.  # noqa: E501
        :rtype: Error
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tite(self) -> str:
        """Gets the tite of this Error.


        :return: The tite of this Error.
        :rtype: str
        """
        return self._tite

    @tite.setter
    def tite(self, tite: str):
        """Sets the tite of this Error.


        :param tite: The tite of this Error.
        :type tite: str
        """

        self._tite = tite

    @property
    def status(self) -> int:
        """Gets the status of this Error.


        :return: The status of this Error.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status: int):
        """Sets the status of this Error.


        :param status: The status of this Error.
        :type status: int
        """

        self._status = status

    @property
    def detail(self) -> str:
        """Gets the detail of this Error.


        :return: The detail of this Error.
        :rtype: str
        """
        return self._detail

    @detail.setter
    def detail(self, detail: str):
        """Sets the detail of this Error.


        :param detail: The detail of this Error.
        :type detail: str
        """

        self._detail = detail

    @property
    def type(self) -> str:
        """Gets the type of this Error.


        :return: The type of this Error.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this Error.


        :param type: The type of this Error.
        :type type: str
        """

        self._type = type
