# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class EventList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, member_list: List[ERRORUNKNOWN]=None):  # noqa: E501
        """EventList - a model defined in Swagger

        :param member_list: The member_list of this EventList.  # noqa: E501
        :type member_list: List[ERRORUNKNOWN]
        """
        self.swagger_types = {
            'member_list': List[ERRORUNKNOWN]
        }

        self.attribute_map = {
            'member_list': 'member_list'
        }

        self._member_list = member_list

    @classmethod
    def from_dict(cls, dikt) -> 'EventList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EventList of this EventList.  # noqa: E501
        :rtype: EventList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def member_list(self) -> List[ERRORUNKNOWN]:
        """Gets the member_list of this EventList.


        :return: The member_list of this EventList.
        :rtype: List[ERRORUNKNOWN]
        """
        return self._member_list

    @member_list.setter
    def member_list(self, member_list: List[ERRORUNKNOWN]):
        """Sets the member_list of this EventList.


        :param member_list: The member_list of this EventList.
        :type member_list: List[ERRORUNKNOWN]
        """

        self._member_list = member_list
