# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MemberCreate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, username: str=None, name: str=None, email: str=None, password: str=None, description: str=None):  # noqa: E501
        """MemberCreate - a model defined in Swagger

        :param username: The username of this MemberCreate.  # noqa: E501
        :type username: str
        :param name: The name of this MemberCreate.  # noqa: E501
        :type name: str
        :param email: The email of this MemberCreate.  # noqa: E501
        :type email: str
        :param password: The password of this MemberCreate.  # noqa: E501
        :type password: str
        :param description: The description of this MemberCreate.  # noqa: E501
        :type description: str
        """
        self.swagger_types = {
            'username': str,
            'name': str,
            'email': str,
            'password': str,
            'description': str
        }

        self.attribute_map = {
            'username': 'username',
            'name': 'name',
            'email': 'email',
            'password': 'password',
            'description': 'description'
        }

        self._username = username
        self._name = name
        self._email = email
        self._password = password
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'MemberCreate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Member_Create of this MemberCreate.  # noqa: E501
        :rtype: MemberCreate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self) -> str:
        """Gets the username of this MemberCreate.


        :return: The username of this MemberCreate.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this MemberCreate.


        :param username: The username of this MemberCreate.
        :type username: str
        """

        self._username = username

    @property
    def name(self) -> str:
        """Gets the name of this MemberCreate.


        :return: The name of this MemberCreate.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this MemberCreate.


        :param name: The name of this MemberCreate.
        :type name: str
        """

        self._name = name

    @property
    def email(self) -> str:
        """Gets the email of this MemberCreate.


        :return: The email of this MemberCreate.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this MemberCreate.


        :param email: The email of this MemberCreate.
        :type email: str
        """

        self._email = email

    @property
    def password(self) -> str:
        """Gets the password of this MemberCreate.


        :return: The password of this MemberCreate.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this MemberCreate.


        :param password: The password of this MemberCreate.
        :type password: str
        """

        self._password = password

    @property
    def description(self) -> str:
        """Gets the description of this MemberCreate.


        :return: The description of this MemberCreate.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this MemberCreate.


        :param description: The description of this MemberCreate.
        :type description: str
        """

        self._description = description
