# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
import re  # noqa: F401,E501
from swagger_server import util


class Member(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, name: str=None, username: str=None, email: str=None, description: str=None):  # noqa: E501
        """Member - a model defined in Swagger

        :param id: The id of this Member.  # noqa: E501
        :type id: int
        :param name: The name of this Member.  # noqa: E501
        :type name: str
        :param username: The username of this Member.  # noqa: E501
        :type username: str
        :param email: The email of this Member.  # noqa: E501
        :type email: str
        :param description: The description of this Member.  # noqa: E501
        :type description: str
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'username': str,
            'email': str,
            'description': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'username': 'username',
            'email': 'email',
            'description': 'description'
        }

        self._id = id
        self._name = name
        self._username = username
        self._email = email
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'Member':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Member of this Member.  # noqa: E501
        :rtype: Member
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Member.


        :return: The id of this Member.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Member.


        :param id: The id of this Member.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Member.


        :return: The name of this Member.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Member.


        :param name: The name of this Member.
        :type name: str
        """

        self._name = name

    @property
    def username(self) -> str:
        """Gets the username of this Member.


        :return: The username of this Member.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this Member.


        :param username: The username of this Member.
        :type username: str
        """
        if username is not None and not re.search('^[a-zA-Z0-9-]+$', username):  # noqa: E501
            raise ValueError("Invalid value for `username`, must be a follow pattern or equal to `/^[a-zA-Z0-9-]+$/`")  # noqa: E501

        self._username = username

    @property
    def email(self) -> str:
        """Gets the email of this Member.


        :return: The email of this Member.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this Member.


        :param email: The email of this Member.
        :type email: str
        """

        self._email = email

    @property
    def description(self) -> str:
        """Gets the description of this Member.


        :return: The description of this Member.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Member.


        :param description: The description of this Member.
        :type description: str
        """

        self._description = description
