# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MemberPublic(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, name: str=None, description: str=None, username: str=None):  # noqa: E501
        """MemberPublic - a model defined in Swagger

        :param id: The id of this MemberPublic.  # noqa: E501
        :type id: int
        :param name: The name of this MemberPublic.  # noqa: E501
        :type name: str
        :param description: The description of this MemberPublic.  # noqa: E501
        :type description: str
        :param username: The username of this MemberPublic.  # noqa: E501
        :type username: str
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'description': str,
            'username': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'description': 'description',
            'username': 'username'
        }

        self._id = id
        self._name = name
        self._description = description
        self._username = username

    @classmethod
    def from_dict(cls, dikt) -> 'MemberPublic':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Member_Public of this MemberPublic.  # noqa: E501
        :rtype: MemberPublic
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this MemberPublic.


        :return: The id of this MemberPublic.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this MemberPublic.


        :param id: The id of this MemberPublic.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this MemberPublic.


        :return: The name of this MemberPublic.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this MemberPublic.


        :param name: The name of this MemberPublic.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this MemberPublic.


        :return: The description of this MemberPublic.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this MemberPublic.


        :param description: The description of this MemberPublic.
        :type description: str
        """

        self._description = description

    @property
    def username(self) -> str:
        """Gets the username of this MemberPublic.


        :return: The username of this MemberPublic.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this MemberPublic.


        :param username: The username of this MemberPublic.
        :type username: str
        """

        self._username = username
