# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.image import Image  # noqa: F401,E501
from swagger_server import util


class MemberPrivate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, name: str=None, email: str=None, description: str=None, images: List[Image]=None, username: str=None):  # noqa: E501
        """MemberPrivate - a model defined in Swagger

        :param id: The id of this MemberPrivate.  # noqa: E501
        :type id: int
        :param name: The name of this MemberPrivate.  # noqa: E501
        :type name: str
        :param email: The email of this MemberPrivate.  # noqa: E501
        :type email: str
        :param description: The description of this MemberPrivate.  # noqa: E501
        :type description: str
        :param images: The images of this MemberPrivate.  # noqa: E501
        :type images: List[Image]
        :param username: The username of this MemberPrivate.  # noqa: E501
        :type username: str
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'email': str,
            'description': str,
            'images': List[Image],
            'username': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'email': 'email',
            'description': 'description',
            'images': 'images',
            'username': 'username'
        }

        self._id = id
        self._name = name
        self._email = email
        self._description = description
        self._images = images
        self._username = username

    @classmethod
    def from_dict(cls, dikt) -> 'MemberPrivate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Member_Private of this MemberPrivate.  # noqa: E501
        :rtype: MemberPrivate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this MemberPrivate.


        :return: The id of this MemberPrivate.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this MemberPrivate.


        :param id: The id of this MemberPrivate.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this MemberPrivate.


        :return: The name of this MemberPrivate.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this MemberPrivate.


        :param name: The name of this MemberPrivate.
        :type name: str
        """

        self._name = name

    @property
    def email(self) -> str:
        """Gets the email of this MemberPrivate.


        :return: The email of this MemberPrivate.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this MemberPrivate.


        :param email: The email of this MemberPrivate.
        :type email: str
        """

        self._email = email

    @property
    def description(self) -> str:
        """Gets the description of this MemberPrivate.


        :return: The description of this MemberPrivate.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this MemberPrivate.


        :param description: The description of this MemberPrivate.
        :type description: str
        """

        self._description = description

    @property
    def images(self) -> List[Image]:
        """Gets the images of this MemberPrivate.


        :return: The images of this MemberPrivate.
        :rtype: List[Image]
        """
        return self._images

    @images.setter
    def images(self, images: List[Image]):
        """Sets the images of this MemberPrivate.


        :param images: The images of this MemberPrivate.
        :type images: List[Image]
        """

        self._images = images

    @property
    def username(self) -> str:
        """Gets the username of this MemberPrivate.


        :return: The username of this MemberPrivate.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this MemberPrivate.


        :param username: The username of this MemberPrivate.
        :type username: str
        """

        self._username = username
