# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Social(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, media_name: str=None, link: str=None):  # noqa: E501
        """Social - a model defined in Swagger

        :param media_name: The media_name of this Social.  # noqa: E501
        :type media_name: str
        :param link: The link of this Social.  # noqa: E501
        :type link: str
        """
        self.swagger_types = {
            'media_name': str,
            'link': str
        }

        self.attribute_map = {
            'media_name': 'mediaName',
            'link': 'link'
        }

        self._media_name = media_name
        self._link = link

    @classmethod
    def from_dict(cls, dikt) -> 'Social':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Social of this Social.  # noqa: E501
        :rtype: Social
        """
        return util.deserialize_model(dikt, cls)

    @property
    def media_name(self) -> str:
        """Gets the media_name of this Social.


        :return: The media_name of this Social.
        :rtype: str
        """
        return self._media_name

    @media_name.setter
    def media_name(self, media_name: str):
        """Sets the media_name of this Social.


        :param media_name: The media_name of this Social.
        :type media_name: str
        """

        self._media_name = media_name

    @property
    def link(self) -> str:
        """Gets the link of this Social.


        :return: The link of this Social.
        :rtype: str
        """
        return self._link

    @link.setter
    def link(self, link: str):
        """Sets the link of this Social.


        :param link: The link of this Social.
        :type link: str
        """

        self._link = link
