# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Success(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, success: bool=None, description: str=None):  # noqa: E501
        """Success - a model defined in Swagger

        :param success: The success of this Success.  # noqa: E501
        :type success: bool
        :param description: The description of this Success.  # noqa: E501
        :type description: str
        """
        self.swagger_types = {
            'success': bool,
            'description': str
        }

        self.attribute_map = {
            'success': 'success',
            'description': 'description'
        }

        self._success = success
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'Success':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Success of this Success.  # noqa: E501
        :rtype: Success
        """
        return util.deserialize_model(dikt, cls)

    @property
    def success(self) -> bool:
        """Gets the success of this Success.


        :return: The success of this Success.
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success: bool):
        """Sets the success of this Success.


        :param success: The success of this Success.
        :type success: bool
        """

        self._success = success

    @property
    def description(self) -> str:
        """Gets the description of this Success.


        :return: The description of this Success.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Success.


        :param description: The description of this Success.
        :type description: str
        """

        self._description = description
